#!/bin/bash

build-book() {
    local book
    book=$1
    
    mkdir -p target
    cat "books/template.abc" books/${book}/*.abc >"target/${book}.abc"
    abcm2ps "target/${book}.abc" -O "target/${book}.ps"
    ps2pdf "target/${book}.ps" "target/${book}.pdf"
}


build-book usa-scout
build-book english-nursery
build-book magyar-gyerekdalok
