#!/bin/bash

mkdir -p target
cat books/template.abc books/english-nursery/*.abc >target/english-nursery.abc
abcm2ps target/english-nursery.abc -O target/english-nursery.ps
ps2pdf target/english-nursery.ps target/english-nursery.pdf

