#!/bin/bash

build-book() {
    local book
    book=$1

    echo "Building: $book"
    mkdir -p target
    cat "books/template.abc" books/${book}/*.abc >"target/${book}.abc"
    abcm2ps "target/${book}.abc" -O "target/${book}.ps"
    ps2pdf "target/${book}.ps" "target/${book}.pdf"
}


for book in books/*
do
    if [[ -d ${book} ]]; then	
	bookname=$(basename $book)
	build-book $bookname
    fi
done
