#!/bin/bash

mkdir -p target
mkdir -p target/english-nursery
for song in books/english-nursery/*.abc
do
    song_file=$(basename "${song}")
   cat books/template.abc "${song}" >"target/english-nursery/${song_file}"
   abcm2ps "target/english-nursery/${song_file}" -O "target/english-nursery/${song_file}.ps"
   ps2pdf "target/english-nursery/${song_file}.ps" "target/english-nursery/${song_file}.pdf"    
done
	    


