#!/bin/bash

build-pages() {
    local book
    book=$1
    mkdir -p target/${book}
    for song in books/${book}/*.abc
    do
	song_file=$(basename "${song}")
	cat books/template.abc "${song}" >"target/${book}/${song_file}"
	abcm2ps "target/${book}/${song_file}" -O "target/${book}/${song_file}.ps"
	ps2pdf "target/${book}/${song_file}.ps" "target/${book}/${song_file}.pdf"    
    done    
}

mkdir -p target
build-pages english-nursery
build-pages usa-scout


